In [1]:
import numpy as np

def gauss_jordan_pivoting(A, b):
    n = len(b)

    Ab = np.hstack([A, b.reshape(-1, 1)]).astype(float)

    print("Matriks Augmented Awal:")
    print(Ab)
    print("-" * 20)

    for k in range(n):

        p = k + np.argmax(np.abs(Ab[k:, k]))


        if p != k:
            Ab[[k, p]] = Ab[[p, k]]
            print(f"Swap baris {k} dengan baris {p}")


        pivot = Ab[k, k]
        if abs(pivot) < 1e-12:
            raise ValueError("Matriks singular, tidak ada solusi unik.")

        Ab[k] = Ab[k] / pivot


        for i in range(n):
            if i != k:
                faktor = Ab[i, k]
                Ab[i] = Ab[i] - faktor * Ab[k]

    return Ab[:, -1]


A = np.array([
    [15, -5, -2, 0],
    [-5, 20, -8, -3],
    [-2, -8, 25, -10],
    [0, -3, -10, 30]
])

b = np.array([10, 0, -5, 15])


try:
    solusi = gauss_jordan_pivoting(A, b)

    print("\n--- Hasil Akhir ---")
    for idx, arus in enumerate(solusi):
        print(f"Arus i{idx+1} = {arus:.4f} A")


    check = np.linalg.solve(A, b)
    print(f"\nVerifikasi Numpy: {check}")

except Exception as e:
    print(f"Terjadi kesalahan: {e}")

Matriks Augmented Awal:
[[ 15.  -5.  -2.   0.  10.]
 [ -5.  20.  -8.  -3.   0.]
 [ -2.  -8.  25. -10.  -5.]
 [  0.  -3. -10.  30.  15.]]
--------------------

--- Hasil Akhir ---
Arus i1 = 0.8315 A
Arus i2 = 0.3977 A
Arus i3 = 0.2420 A
Arus i4 = 0.6204 A

Verifikasi Numpy: [0.83150345 0.39772511 0.24196306 0.62042686]
